# Generated by Django 4.2.3 on 2023-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="period_length",
            field=models.DurationField(),
        ),
    ]
