# Generated by Django 4.2.3 on 2023-08-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="stats.season",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="away_full_timeouts_taken",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="away_s30_timeouts_taken",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="counts_towards_record",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_full_timeouts_taken",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_s30_timeouts_taken",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="period",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="game",
            name="time_on_clock",
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name="teamseason",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="stats.division",
            ),
        ),
        migrations.DeleteModel(
            name="DivisionSeason",
        ),
    ]
