# Generated by Django 4.2.3 on 2023-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_game_season_alter_game_away_full_timeouts_taken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamseason",
            name="head_coach",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
