# Generated by Django 4.2.3 on 2023-08-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_alter_teamseason_head_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamseason",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="stats.team",
            ),
        ),
    ]
