# Generated by Django 4.2.3 on 2023-08-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_team_logo 2"),
        ("stats", "0006_alter_teamseason_head_coach 2"),
        ("stats", "0007_alter_teamseason_team"),
        ("stats", "0007_alter_teamseason_team 2"),
    ]

    operations = []
