# Generated by Django 4.2.3 on 2023-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_merge_20230820_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="is_open",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
