# Generated by Django 4.2.3 on 2023-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_league_is_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="is_complete",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
